import "./form.less";
import { vpCheckbox } from "./checkbox";
import { vpCheckboxgroup } from "./checkboxgroup";
import { vpRadio } from "./radio";
import { vpRadiogroup } from "./radiogroup";
import { vpInput } from "./input";
import { vpTextarea } from "./textarea";
import { vpSelect } from "./select";
import { vpSwitch } from "./switch";
export { vpCheckbox, vpCheckboxgroup, vpRadio, vpRadiogroup, vpInput, vpTextarea, vpSelect, vpSwitch };